name: 'setup'
description: 'checkout, setup rust and python'
inputs:
  rust-version:
    description: 'Rust version'
    required: true
    default: 'stable'
  extra-targets:
    description: 'Extra Rust targets'
  toolchain-args:
    description: 'Extra args for `rustup toolchain`'
runs:
  using: "composite"
  steps:
    - uses: mhils/workflows/setup-python@3c9fc8f5b40cb8f3f1b81163f3f195cad843b09a  # v18.0  # PyO3 wants recent Python on Windows.
    - run: rustup toolchain install ${{ inputs.rust-version }} --profile minimal ${{ inputs.toolchain-args }}
      shell: bash
    - if: runner.os == 'Linux'
      run: rustup toolchain install nightly --component rust-src
      shell: bash
    - run: rustup default ${{ inputs.rust-version }}
      shell: bash
    - if: inputs.extra-targets
      run: rustup target add ${{ inputs.extra-targets }}
      shell: bash
    - uses: mhils/workflows/rust-cache@5b6540d578f48644ffa5e955cedadc81034cb7d8  # v19.0
      with:
        key: ${{ inputs.rust-version }} # proxy value for glibc version
    - if: runner.os == 'Linux'
      run: cargo install --locked bpf-linker
      shell: bash
