// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ipc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Mitmproxy_Ipc_FromRedirector {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Mitmproxy_Ipc_FromRedirector.OneOf_Message? = nil

  var packet: Mitmproxy_Ipc_FromRedirector.PacketWithMeta {
    get {
      if case .packet(let v)? = message {return v}
      return Mitmproxy_Ipc_FromRedirector.PacketWithMeta()
    }
    set {message = .packet(newValue)}
  }

  var log: Mitmproxy_Ipc_FromRedirector.LogMessage {
    get {
      if case .log(let v)? = message {return v}
      return Mitmproxy_Ipc_FromRedirector.LogMessage()
    }
    set {message = .log(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Message: Equatable {
    case packet(Mitmproxy_Ipc_FromRedirector.PacketWithMeta)
    case log(Mitmproxy_Ipc_FromRedirector.LogMessage)

  #if !swift(>=4.1)
    static func ==(lhs: Mitmproxy_Ipc_FromRedirector.OneOf_Message, rhs: Mitmproxy_Ipc_FromRedirector.OneOf_Message) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.packet, .packet): return {
        guard case .packet(let l) = lhs, case .packet(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.log, .log): return {
        guard case .log(let l) = lhs, case .log(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  struct LogMessage {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var message: String = String()

    var level: Mitmproxy_Ipc_FromRedirector.LogMessage.LogLevel = .notSet

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum LogLevel: SwiftProtobuf.Enum {
      typealias RawValue = Int
      case notSet // = 0
      case debug // = 10
      case info // = 20
      case warning // = 30
      case error // = 40
      case UNRECOGNIZED(Int)

      init() {
        self = .notSet
      }

      init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .notSet
        case 10: self = .debug
        case 20: self = .info
        case 30: self = .warning
        case 40: self = .error
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      var rawValue: Int {
        switch self {
        case .notSet: return 0
        case .debug: return 10
        case .info: return 20
        case .warning: return 30
        case .error: return 40
        case .UNRECOGNIZED(let i): return i
        }
      }

    }

    init() {}
  }

  struct PacketWithMeta {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var data: Data = Data()

    var pid: UInt32 = 0

    var processName: String {
      get {return _processName ?? String()}
      set {_processName = newValue}
    }
    /// Returns true if `processName` has been explicitly set.
    var hasProcessName: Bool {return self._processName != nil}
    /// Clears the value of `processName`. Subsequent reads from it will return its default value.
    mutating func clearProcessName() {self._processName = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _processName: String? = nil
  }

  init() {}
}

#if swift(>=4.2)

extension Mitmproxy_Ipc_FromRedirector.LogMessage.LogLevel: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Mitmproxy_Ipc_FromRedirector.LogMessage.LogLevel] = [
    .notSet,
    .debug,
    .info,
    .warning,
    .error,
  ]
}

#endif  // swift(>=4.2)

struct Mitmproxy_Ipc_FromProxy {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Mitmproxy_Ipc_FromProxy.OneOf_Message? = nil

  var packet: Mitmproxy_Ipc_FromProxy.Packet {
    get {
      if case .packet(let v)? = message {return v}
      return Mitmproxy_Ipc_FromProxy.Packet()
    }
    set {message = .packet(newValue)}
  }

  var interceptSpec: Mitmproxy_Ipc_FromProxy.InterceptSpec {
    get {
      if case .interceptSpec(let v)? = message {return v}
      return Mitmproxy_Ipc_FromProxy.InterceptSpec()
    }
    set {message = .interceptSpec(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Message: Equatable {
    case packet(Mitmproxy_Ipc_FromProxy.Packet)
    case interceptSpec(Mitmproxy_Ipc_FromProxy.InterceptSpec)

  #if !swift(>=4.1)
    static func ==(lhs: Mitmproxy_Ipc_FromProxy.OneOf_Message, rhs: Mitmproxy_Ipc_FromProxy.OneOf_Message) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.packet, .packet): return {
        guard case .packet(let l) = lhs, case .packet(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.interceptSpec, .interceptSpec): return {
        guard case .interceptSpec(let l) = lhs, case .interceptSpec(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  struct Packet {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var data: Data = Data()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct InterceptSpec {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var spec: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Mitmproxy_Ipc_FromRedirector: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromRedirector.OneOf_Message: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromRedirector.LogMessage: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromRedirector.LogMessage.LogLevel: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromRedirector.PacketWithMeta: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromProxy: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromProxy.OneOf_Message: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromProxy.Packet: @unchecked Sendable {}
extension Mitmproxy_Ipc_FromProxy.InterceptSpec: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "mitmproxy.ipc"

extension Mitmproxy_Ipc_FromRedirector: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FromRedirector"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "packet"),
    2: .same(proto: "log"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Mitmproxy_Ipc_FromRedirector.PacketWithMeta?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .packet(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .packet(v)
        }
      }()
      case 2: try {
        var v: Mitmproxy_Ipc_FromRedirector.LogMessage?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .log(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .log(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .packet?: try {
      guard case .packet(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .log?: try {
      guard case .log(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromRedirector, rhs: Mitmproxy_Ipc_FromRedirector) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mitmproxy_Ipc_FromRedirector.LogMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Mitmproxy_Ipc_FromRedirector.protoMessageName + ".LogMessage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "message"),
    2: .same(proto: "level"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.level) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    if self.level != .notSet {
      try visitor.visitSingularEnumField(value: self.level, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromRedirector.LogMessage, rhs: Mitmproxy_Ipc_FromRedirector.LogMessage) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.level != rhs.level {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mitmproxy_Ipc_FromRedirector.LogMessage.LogLevel: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NotSet"),
    10: .same(proto: "Debug"),
    20: .same(proto: "Info"),
    30: .same(proto: "Warning"),
    40: .same(proto: "Error"),
  ]
}

extension Mitmproxy_Ipc_FromRedirector.PacketWithMeta: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Mitmproxy_Ipc_FromRedirector.protoMessageName + ".PacketWithMeta"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "data"),
    2: .same(proto: "pid"),
    3: .standard(proto: "process_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.pid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._processName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if self.pid != 0 {
      try visitor.visitSingularUInt32Field(value: self.pid, fieldNumber: 2)
    }
    try { if let v = self._processName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromRedirector.PacketWithMeta, rhs: Mitmproxy_Ipc_FromRedirector.PacketWithMeta) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.pid != rhs.pid {return false}
    if lhs._processName != rhs._processName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mitmproxy_Ipc_FromProxy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FromProxy"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "packet"),
    2: .standard(proto: "intercept_spec"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Mitmproxy_Ipc_FromProxy.Packet?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .packet(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .packet(v)
        }
      }()
      case 2: try {
        var v: Mitmproxy_Ipc_FromProxy.InterceptSpec?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .interceptSpec(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .interceptSpec(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .packet?: try {
      guard case .packet(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .interceptSpec?: try {
      guard case .interceptSpec(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromProxy, rhs: Mitmproxy_Ipc_FromProxy) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mitmproxy_Ipc_FromProxy.Packet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Mitmproxy_Ipc_FromProxy.protoMessageName + ".Packet"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "data"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromProxy.Packet, rhs: Mitmproxy_Ipc_FromProxy.Packet) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Mitmproxy_Ipc_FromProxy.InterceptSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Mitmproxy_Ipc_FromProxy.protoMessageName + ".InterceptSpec"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "spec"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.spec) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.spec.isEmpty {
      try visitor.visitSingularStringField(value: self.spec, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Mitmproxy_Ipc_FromProxy.InterceptSpec, rhs: Mitmproxy_Ipc_FromProxy.InterceptSpec) -> Bool {
    if lhs.spec != rhs.spec {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
